config/routes.rb
Photon::Application.routes.draw do |map|
  resources :users, :user_session
  resources :albums do
    resources :pictures
  end
  
  match "/login", :to => "user_sessions#new"
  match "/logout", :to => "user_sessions#destroy"
  match "/register", :to => "users#new"
  
  root :to => "albums#index"
end

app/views/shared/_breadcrumb.html.haml
#breadcrumb
  - if current_user
    - if current_user.role.title == "admin"
      - if flash[:warning] or flash[:notice]
        - if flash[:warning]
          .flashWarning
        - else
          .flashNotice
        = flash[:warning] || flash[:notice]
      - if Picture.to_process.count > 0
        Pictures to process:
        = Picture.to_process.count
      - else
        No pictures to process.

app/views/shared/_error_messages.html.haml
- if target.errors.any?
  #errorExplanation
  %h2
    = pluralize(target.errors.count, "erreur")
    = translate("prohibited_form_being_saved", :count => target.errors.count)
  %ul
    - target.errors.full_messages.each do |msg|
      %li= msg
  %br

app/views/shared/_footer.html.haml
Powered by
= link_to "Photon", "http://github.com/rhaamo/photon", :target => :_blank

app/views/shared/_head.html.haml
%meta{ :content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }
= javascript_include_tag :defaults
= javascript_include_tag "http://openlayers.org/api/OpenLayers.js"
= javascript_include_tag "map"
= stylesheet_link_tag 'application'
= csrf_meta_tag
= yield :head

app/views/shared/_header.html.haml
#title
  = link_to "Photon", root_path
#links.clearfix
  %ul
    %li= link_to t(:header_tab_home), root_path
    - if controller_name == "pictures"
      %li= link_to t(:header_tab_return_album), @album
    - if !["index", "new", "create"].include? action_name
      - if !["users"].include? controller_name
        - if (current_user.role.title == "admin" if current_user)
          %li= link_to t(:header_tab_edit_album), edit_album_path(@album)
    - if current_user
      %li
        Connected as
        = current_user.login
        - if current_user.role.title == "admin"
          %a{:title => "admin"} (A)
          - if action_name != "show"
            %li= link_to t(:header_tab_album_new), new_album_path
      %li= link_to t(:header_tab_account), edit_user_path(current_user)
      %li= link_to t(:header_tab_logout), logout_path
    - else
      %li= link_to t(:header_tab_login), login_path
      %li= link_to t(:header_tab_register), new_user_path

app/views/shared/footer.html.haml
Powered by Photon