config/routes.rb
Photon::Application.routes.draw do |map|
  resources :users, :user_session
  resources :albums do
    resources :pictures
  end
  
  match "/login", :to => "user_sessions#new"
  match "/logout", :to => "user_sessions#destroy"
  match "/register", :to => "users#new"
  
  root :to => "albums#index"
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
  belongs_to :album
  has_one :exif

  mount_uploader :photo, PhotoUploader

  after_create :process_exif
  after_create :create_other_sizes
  after_destroy :delete_other_sizes
  scope :processed, lambda { { :conditions => ['photo_processing = ?', false] } }
  scope :processing, lambda { { :conditions => ['photo_processing = ?', true] } }
  scope :to_process, lambda { { :conditions => ['to_process = ?', true] } }

  def delete_other_sizes
    # Run it in background
    puts self.photo.path
    Delayed::Job.enqueue ProcessDeleteOtherSizesJob.new(self.photo.path), 0, Time.at(Time.now)
  end

  def process_exif
    file = self.photo.path
    if File.exist? file
      begin
        exif = EXIFR::JPEG.new file
      rescue
        exif = nil
      end
      pic_exif = self.build_exif
      if exif
        pic_exif.width  = exif.width
        pic_exif.height = exif.height
        pic_exif.camera_brand = exif.make
        pic_exif.camera_model = exif.model
        pic_exif.exposure_time = exif.exposure_time.to_s
        pic_exif.f_number = exif.f_number.to_f
        pic_exif.iso_speed_rating = exif.iso_speed_ratings
        pic_exif.focale_length = exif.focal_length.to_f
        pic_exif.shot_date_time = exif.date_time
        pic_exif.flash = exif.flash
        begin
          lat = exif.gps_latitude
          lon = exif.gps_longitude
          pic_exif.gps_latitude = calc_gps(lat) if lat
          pic_exif.gps_longitude = calc_gps(lon) if lon
        end
      else
        pic_exif.no_exif = true
      end
      pic_exif.save
    else
      # WTF, srsly, delete broken record. sorry.
      self.destroy
    end
  end
  
  def create_other_sizes
    # Run this -can be long- task in background
    Delayed::Job.enqueue ProcessResizesJob.new(self.id), 0, Time.at(Time.now)
  end
  
  private
  def calc_gps(lalon)
    deg = lalon[0]
    min = lalon[1]
    sec = lalon[2]
    dec_min = (min.to_f + sec.to_f/60)
    decimals = (deg.to_f + dec_min.to_f/60)
    return decimals
  end
  
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  layout :set_layout
  before_filter :require_user, :except => [:index, :show]
  before_filter :require_admin, :except => [:index, :show]
  
  def index
    @album = Album.find(params[:album_id])
    @pictures = @album.pictures.processed
  end
  
  def show
    @album = Album.find(params[:album_id])
    @picture = Picture.find(params[:id])
  end
  
  private
  def set_layout
    l = "application"
    if action_name == "index"
      l = "album_layout"
    end
    if action_name == "show"
      l = "picture_layout"
    end
    return l
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def get_picture_url(photo, p_size = :original)
    store_dir = File.dirname(photo.store_dir)
    if [:large, :medium, :normal, :small, :thumb, :original].include? p_size
      return File.join("/", store_dir, p_size.to_s, File.basename(photo.path))
    else
      return File.join("/", store_dir, "default", "invalid.png")
    end
  end
  
  def navigation_objects(album, photo)
    # Return three objects
    index_in_album = album.pictures.index(photo)
    album_size = (album.pictures.size-1)
    pictures = album.pictures
    
    case index_in_album
      when 0
        # first
        # Return actual act+1 act+2
        return [photo, pictures[1], pictures[2]]
      when album_size
        # last
        # return act act-1 act-2
        return [pictures[album_size-2], pictures[album_size-1], photo]
      else
        # not first and not last :D
        # return act-1 act act+1
        return [pictures[index_in_album-1], photo, pictures[index_in_album+1]]
    end
  end
    
end

app/views/pictures/_exif.html.haml
= t(:exif_data, :scope => [:exif])
#exifDatas
  = t(:image_width, :scope => [:exif])
  = @picture.exif.width
  %br
  = t(:image_height, :scope => [:exif])
  = @picture.exif.height
  %br
  - if @picture.exif.gps_latitude and @picture.exif.gps_longitude
    = t(:longitude, :scope => [:exif])
    = @picture.exif.gps_longitude
    %br
    = t(:latitude, :scope => [:exif])
    = @picture.exif.gps_latitude
    %br
  = t(:camera_model, :scope => [:exif])
  = @picture.exif.camera_model
  %br
  = t(:camera_brand, :scope => [:exif])
  = @picture.exif.camera_brand
  %br
  = t(:exposure_time, :scope => [:exif])
  = @picture.exif.exposure_time
  %br
  = t(:f_number, :scope => [:exif])
  = @picture.exif.f_number
  %br
  = t(:iso, :scope => [:exif])
  = @picture.exif.iso_speed_rating
  %br
  = t(:focale_length, :scope => [:exif])
  = @picture.exif.focale_length
  %br
  = t(:picture_date, :scope => [:exif])
  = @picture.exif.shot_date_time
  %br
  = t(:flash_mode, :scope => [:exif])
  = t "mode#{@picture.exif.flash || 'nil'}".to_sym, :scope => [:exif, :flash]

app/views/pictures/_infos.html.haml
Accès direct aux differentes tailles:
#sizeList
  %table.listOfPhotoSizes
    %tr
      %td
        &raquo; 
        = link_to "Original", get_picture_url(@picture.photo, :original)
      %td
        &raquo; 
        = link_to "Large", get_picture_url(@picture.photo, :large)
      %td
        &raquo; 
        = link_to "Normal", get_picture_url(@picture.photo, :normal)
    %tr
      %td
        &raquo; 
        = link_to "Medium", get_picture_url(@picture.photo, :medium)
      %td
        &raquo; 
        = link_to "Small", get_picture_url(@picture.photo, :small)
      %td
        &raquo; 
        = link_to "Thumbnail", get_picture_url(@picture.photo, :thumb)

app/views/pictures/_map.html.haml
- if @picture.exif.gps_latitude and @picture.exif.gps_longitude
  #map
  %script{:type => "text/javascript"}
    = "var long = #{@picture.exif.gps_longitude}"
    = "var lati = #{@picture.exif.gps_latitude}"
    var theDiv = 'map'
    initOpenLayerMap(long, lati, theDiv);

app/views/pictures/_navigation.html.haml
- navigation = navigation_objects(@album, @picture)
- [0,1,2].each do |nav|
  - if navigation[nav].nil?
  - else
    .pictureNavigation
      = link_to image_tag(get_picture_url(navigation[nav].photo, :thumb)), album_picture_path(@album, navigation[nav])

app/views/pictures/show.html.haml
= content_for :head do
  %title
    = t(:title_pictures_show)
    \-
    = t(:application_name)

#left
  %span.pictureName= @picture.name
  = image_tag get_picture_url(@picture.photo, :normal)

#right
  - if !@picture.exif.no_exif
    = render :partial => "map"
  #navigation
    = render :partial => "navigation"
  #pictureInfos
    = render :partial => "infos"
  #exif
    - if !@picture.exif.no_exif
      = render :partial => "exif"